# PyTorch Tutorial 03: Define Networks
## Overview
In this tutorial, we explain how to define networks. 

In [1]:
import torch 
import torch.nn as nn


In [2]:
x = torch.rand([8, 100, 10]).detach()
x 

tensor([[[0.1283, 0.7627, 0.0181,  ..., 0.8569, 0.4531, 0.4337],
         [0.3366, 0.5344, 0.2687,  ..., 0.2099, 0.7453, 0.0209],
         [0.4089, 0.6110, 0.5130,  ..., 0.1261, 0.9310, 0.4383],
         ...,
         [0.2976, 0.0961, 0.5546,  ..., 0.8212, 0.6335, 0.3497],
         [0.3701, 0.0833, 0.4147,  ..., 0.2035, 0.4569, 0.4486],
         [0.2438, 0.6422, 0.8251,  ..., 0.3859, 0.9151, 0.4302]],

        [[0.2359, 0.1646, 0.9636,  ..., 0.1148, 0.2140, 0.5944],
         [0.3071, 0.6690, 0.1750,  ..., 0.1503, 0.1939, 0.9889],
         [0.4855, 0.2156, 0.6161,  ..., 0.2892, 0.8562, 0.4031],
         ...,
         [0.7569, 0.7194, 0.5767,  ..., 0.4001, 0.1561, 0.0242],
         [0.7725, 0.8491, 0.1711,  ..., 0.9211, 0.9180, 0.9002],
         [0.8873, 0.2162, 0.2717,  ..., 0.4897, 0.5422, 0.9277]],

        [[0.2835, 0.1043, 0.4089,  ..., 0.8274, 0.1067, 0.7595],
         [0.4789, 0.1006, 0.1152,  ..., 0.2405, 0.4191, 0.4407],
         [0.3027, 0.0196, 0.8439,  ..., 0.3833, 0.7521, 0.

In [3]:
y = torch.rand(8)
y = (y>0.5).int()
y

tensor([1, 1, 0, 1, 1, 0, 0, 1], dtype=torch.int32)

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.first_layer = nn.Linear(1000,50)
        self.second_layer = nn.Linear(50, 1)
    def forward(self, x):
        x = torch.flatten(x, start_dim=1, end_dim=2)
        x = nn.functional.relu(self.first_layer(x))
        x = self.second_layer(x)
        return x

In [5]:
mlp = MLP()
output = mlp(x)

In [6]:
output

tensor([[-0.1030],
        [-0.2689],
        [-0.1698],
        [-0.1140],
        [-0.3090],
        [-0.1686],
        [-0.2050],
        [-0.1751]], grad_fn=<AddmmBackward>)

In [7]:
class Embedding(nn.Module):
    def __init__(self):
        super(Embedding, self).__init__()
        self.embedding = nn.Embedding(4, 100)
    def forward(self, x):
        return self.embedding(x)

In [8]:
embedding = Embedding()

embedding_input = torch.tensor([[0,1, 0],[2,3, 3]])
embedding_output = embedding(embedding_input)

In [9]:
embedding_output.shape

torch.Size([2, 3, 100])

In [10]:
class LSTM(nn.Module):
    def __init__(self):
        super(LSTM, self).__init__()
        self.lstm = nn.LSTM(10, 
                           15, 
                           num_layers=2, 
                           bidirectional=True, 
                           dropout=0.1)
    def forward(self, x):
        output, (hidden, cell) = self.lstm(x)
        return output, hidden, cell

In [11]:
permute_x = x.permute([1,0,2])
lstm = LSTM()
output_lstm1, output_lstm2, output_lstm3 = lstm(permute_x)

In [12]:
output_lstm2.shape

torch.Size([4, 8, 15])

In [13]:
class Conv(nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv1d = nn.Conv1d(100, 50, 2)
    def forward(self, x):
        return self.conv1d(x)

In [14]:
conv = Conv()
output = conv(x)

In [15]:
output.shape

torch.Size([8, 50, 9])